---
name: Bug Report
description: Is something wrong with Celery?
labels: 'Issue Type: Bug Report'
body:
- type: checkboxes
  id: checklist
  attributes: 
    label: Checklist
    description: 
    options:
    - label: "I have verified that the issue exists against the `master` branch of Celery"
    - label: "This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first"
    - label: "I have read the relevant section in the [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs) on reporting bugs"
    - label: "I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22) for similar or identical bug reports"
    - label: "I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22) for existing proposed fixes"
    - label: "I have checked the [commit log](https://github.com/celery/celery/commits/master) to find out if the bug was already fixed in the master branch"
    - label: "I have included all related issues and possible duplicate issues in this issue (If there are none, check this box anyway)"
  validations: 
    requierd: true
    
- type: textarea
  id: mrtc
  attributes:
    label: Minimally Reproducible Test Case
    description: "Provide a code sample which is the most minimal example possible for reproducing the bug (Paste a Gist or a link to a Github repository if the MRTC is too long)"
    placeholder: |
      We prefer submitting test cases in the form of a PR to our integration test suite
      If you can provide one, please mention the PR number below
      If not, please attach the most minimal code example required to reproduce the issue below
      If the test case is too large, please include a link to a gist or a repository below
    render: python3
  validations:
   required: true
   
- type: textarea
  id: repro
  attributes:
    label: Expected Behavior
    description: "Describe in detail what you expect to happen"
  validations:
    required: true
    
- type: textarea
  id: actual
  attributes:
    label: Actual Behavior
    description: "Describe in detail what actually happened"
    placeholder: |
      Please include a backtrace and surround it with triple backticks (```).
      In addition, include the Celery daemon logs, the broker logs,
      the result backend logs and system logs below if they will help us debug the issue
  validations:
    required: true
    
- type: dropdown
  id: python_version
  attributes:
    label: Minimal Python Version
    description: Please select the minimal Python supported version
    options: 
    - 3.7
    - 3.8
    - 3.9
    - '3.10'
  validations:
    required: true

- type: dropdown
  id: celery_version
  attributes:
    label: Minimal Celery Version
    description: Please select the minimal Celery supported version
    options: 
    - '5.0'
    - 5.1
    - 5.2

  validations:
    required: true

- type: dropdown
  id: Kombu_version
  attributes: 
    label: Minimal Kombu Version
    description: Please select the minimal Kombu supported version
    options: 
    - 4.6
    - '5.0'
    - 5.1
    - 5.2 

  validations:
    required: true
    
- type: textarea
  id: python_package
  attributes:
    label: Python Packages
    description: Please fill the contents of pip freeze below
      
  validations:
    required: true
    
---
