---
name: Bug Report
description: Is something wrong with Celery?
labels: 'Issue Type: Bug Report'
body:
- type: textarea
  id: mrtc
  attributes:
    label: Minimally Reproducible Test Case
    description: "Provide a code sample which is the most minimal example possible for reproducing the bug (Paste a Gist or a link to a Github repository if the MRTC is too long)"
    render: python3
  validations:
   required: true
- type: textarea
  id: repro
  attributes:
    label: Expected Behavior
    description: "Describe in detail what you expect to happen"
  validations:
    required: true
- type: dropdown
  id: python_version
  attributes:
    label: Minimal Python Version
    description: 
    options: 
    - 3.7
    - 3.8
    - 3.9
    - '3.10'
  validations:
    required: true

- type: dropdown
  id: celery_version
  attributes:
    label: Minimal Celery Version
    description: 
    options: 
    - '5.0'
    - 5.1
    - 5.2

  validations:
    required: true

- type: dropdown
  id: Kombu_version
  attributes:
    label: Minimal Kombu Version
    description: 
    options: 
    - 4.6
    - '5.0'
    - 5.1
    - 5.2

  validations:
    required: true
---
